### ISSUE TITLE
Migrate to poetry

### ISSUE THREAD

**Issue by JonathanPlasse** [sbtinstruments/aiomqtt#186]
> In a similar vein, we could also move to the poetry dependency manager, add isort, etc. I just never got around to "modernizing" asyncio-mqtt.

_Originally posted by @frederikaalund in https://github.com/sbtinstruments/asyncio-mqtt/issues/43#issuecomment-786475539_

We could use [poetry-dynamic-versioning](https://github.com/mtkennerly/poetry-dynamic-versioning) to keep the same behavior as `setuptools_scm`.

**Comment by frederikaalund** [comment]
Good idea! I've good personal experience with the [poetry-dynamic-versioning](https://github.com/mtkennerly/poetry-dynamic-versioning) plug-in (or similar) in other projects.
