### ISSUE TITLE
asyncio_mqtt.error.MqttCodeError: [code:7] The connection was lost when using time.sleep in on message callback

### ISSUE THREAD

**Issue by JouvinLea** [sbtinstruments/aiomqtt#219]
Hi all,

I am using the asyncio mqtt client for asynchrone communication and I encountered an issue that was complicated to solve since the only error I got was:

```
asyncio_mqtt.error.MqttCodeError: [code:7] The connection was lost.
```

I am using the latest release version. Here is some line of code to reproduce the error :

```
import asyncio
import json
import time
from asyncio_mqtt import Client
import sys
import logging
logging.basicConfig(
    stream=sys.stdout,
    level=logging.INFO,
    format="%(asctime)s %(levelname)s [%(name)s] %(message)s",
)

log = logging.getLogger("test")


# Sample async function to be called
async def process(data):
    log.info("Process ", data)
    time.sleep(3*60)
    #await asyncio.sleep(60.*3)

# This gets called whenever when we get an MQTT message
async def mqtt_on_message(msg):
    data = json.loads(msg.payload.decode('utf-8'))
    log.info(data)
    return await process(data=data)

async def main():
    topic="test"
    async with Client(hostname=host,port=port,username=user,password=password, clean_session=False, client_id=client_id) as client:
        async with client.filtered_messages(topic) as messages:
            await client.subscribe(topic, qos=2)
            async for message in messages:
                asyncio.ensure_future(mqtt_on_message(message)) #I've just changed this line of code

if __name__ == "__main__":
    # execute only if run as a script
    asyncio.run(main())

```

The error occurred only if you put a synchrone method time.sleep in the on message callback. It happens only if you use 3 minutes in time.sleep, if you try with 2 minutes for example, no problem. If we use await asyncio.sleep(60.*3), in this case there is no issue.

My first question is do you have any idea why this is happening and from where is coming the disconnection ? My second question is : is there a way to improve the disconnect message error because the code 7 is not very helping ?

Thank you very much,
Léa

**Comment by vvanglro** [comment]
Using `time.sleep` will block the scheduling of the `event loop`, Cause the client to fail to send `PINGREQ`[(About send PINGREQ),](https://github.com/sbtinstruments/asyncio-mqtt/blob/main/asyncio_mqtt/client.py#L820) The broker will disconnect.

1. The following is a reference([mqtt-keep-alive](https://www.emqx.com/en/blog/mqtt-keep-alive)):

      - Broker process
      
        After the connection is established, if the broker does not receive any packets from the client within 1.5 times the Keep Alive time, it will assume that there is a problem with the connection to the client, and the broker will disconnect from the client.


2. Calculation of sleep time:
    ```
    Keepalive * backoff * 2
    ```
    So after the first 60s, if the heartbeat packet is not received in 90s, the connection will be disconnected.

3. About code 7:

    [error_string](https://github.com/eclipse/paho.mqtt.python/blob/a4cb435ca2864d073ea3e0e18b0407e4bbe85b16/src/paho/mqtt/client.py#L189)

**Comment by frederikaalund** [comment]
@vvanglro already did a great job of detective work to track down what's going on. 👍 

The overall problem here is that you combine async code with blocking calls (`time.sleep`). That's a no-go in the world of async python. You already found the proper async alternative (`asyncio.sleep`). Just use that instead.

If you absolutely need to call a blocking sync function from an async context (e.g., to interface with an old sync API), you usually spawn a thread to do so (via `run_in_executor`). In this case, you don't need to because you already have a direct async replacement for the sync and blocking `time.sleep`: `asyncio.sleep`.

I could write out a lengthy reply but it really just boils down to the above. :) I hope that helps!

**Comment by JouvinLea** [comment]
Hi @vvanglro  and @frederikaalund ,

sorry for the late answer I didn't see your answers.

Than you very much for all the explanations and details link, it is pretty clear now!

**Comment by frederikaalund** [comment]
Great to hear, @JouvinLea. :+1: Can I close this issue or do you have further questions? :)

**Comment by JouvinLea** [comment]
You can close it! (-:
