### ISSUE TITLE
Timeout for awaiting messages?

### ISSUE THREAD

**Issue by me21** [sbtinstruments/aiomqtt#222]
I was using the asyncio-mqtt by creating a separate task:

```
async with Client('localhost') as client:
  # subscribe to topics, publish and await messages as needed
```

However, I found that while I'm awaiting on a message, I cannot publish anything. If the message arrives seldom, it limits the outgoing bandwidth. I tried `asyncio.wait_for(messages.__anext__(), timeout=1)`, but the timeout cancels the messages generator, and I have to recreate it. While doing so, I can miss some messages until the generator is recreated.
So I created two separate tasks - one for receiving messages, another one for transmitting. But this leaves me with two client instances (two MQTT connections).
Is it the intended way the library should be used? Is the overhead negligible?

**Comment by frederikaalund** [comment]
Hi Alexandr, thanks for opening this issue. Let me have a look. :)

> However, I found that while I'm awaiting on a message, I cannot publish anything

That sounds weird. It's certainly not what's supposed to happen. 😅 In order to investigate further, I need some more code to look at. Do you have a full code example that reproduces this issue? :)

**Comment by me21** [comment]
Well, I mean I'm able to publish messages, but from a separate task while the first task is awaiting the next message.

Is it how it's supposed to work? Spawn one task for incoming messages and another task for publishing?

**Comment by frederikaalund** [comment]
> Is it how it's supposed to work? Spawn one task for incoming messages and another task for publishing?

Yes, that's it. :) Both tasks can share the same connection (that is, share the same `Client` instance). Does it make sense?

**Comment by frederikaalund** [comment]
> Do I pass the Client instance as a parameter to the tasks?

Yes, exactly. 👍 

> I would like to handle the disconnection event in the tasks and automatically reconnect, how can I achieve this with one Client instance?

Something like this ([taken from the docs](https://sbtinstruments.github.io/asyncio-mqtt/reconnection.html)):

```python
import asyncio
import asyncio_mqtt as aiomqtt

async def subscribe(client):
    async with client.messages() as messages:
        await client.subscribe("humidity/#")
        async for message in messages:
            print(message.payload)

async def publish(client):
    while True:
        await client.publish(...)
        await asyncio.sleep(2)

async def main():
    interval = 5  # Seconds
    while True:
        try:
            async with aiomqtt.Client("test.mosquitto.org") as client:
                async with asyncio.TaskGroup() as tg:
                    tg.create_task(subscribe(client))
                    tg.create_task(publish(client))
        except aiomqtt.MqttError:
            print(f'Connection lost; Reconnecting in {interval} seconds ...')
            await asyncio.sleep(interval)


asyncio.run(main())
```

**Comment by empicano** [comment]
Hi Alexandr,

I'm taking your silence to mean that Frederik's help worked out fine, and we can close this. If there's anything left unclear, or if you think we can improve the docs about this, let us know 😊
