### ISSUE TITLE
Using aiomqtt with fastAPI routers - AttributeError: 'NoneType' object has no attribute 'publish'

### ISSUE THREAD

**Issue by tomliptrot** [sbtinstruments/aiomqtt#230]
Hi,

I'm using aiomqtt in a FastAPI application. I can make it work as expected following your guide [here](https://sbtinstruments.github.io/aiomqtt/side-by-side-with-web-frameworks.html). However, when I try to run it in a larger application that uses routers I run into problems.

My code:

`app.py`
```python
import fastapi

from router import router

app = fastapi.FastAPI()
app.include_router(router, prefix="/mqtt", tags=["mqtt"])
```

`router.py`
```python
import asyncio
import contextlib

import aiomqtt
from fastapi import APIRouter


async def listen(client):
    async with client.messages() as messages:
        await client.subscribe("humidity/#")
        async for message in messages:
            print(message.payload)


client = None


@contextlib.asynccontextmanager
async def lifespan(app):
    global client
    async with aiomqtt.Client("test.mosquitto.org") as c:
        # Make client globally available
        client = c
        # Listen for MQTT messages in (unawaited) asyncio task
        loop = asyncio.get_event_loop()
        task = loop.create_task(listen(client))
        yield
        # Cancel the task
        task.cancel()
        # Wait for the task to be cancelled
        try:
            await task
        except asyncio.CancelledError:
            pass


router = APIRouter(lifespan=lifespan)


@router.get("/")
async def publish():
    await client.publish("humidity/outside", 0.38)
    await client.publish("humidity/outside", 0.38)
```

Running this and then calling the endpoint gives the following error:

```
  File "XXX/router.py", line 42, in publish
    await client.publish("humidity/outside", 0.38)
AttributeError: 'NoneType' object has no attribute 'publish'
```

There is clearly some issue with where the global variable `client`. Any advice on how to solve this would be much appreciated.

**Comment by tomliptrot** [comment]
On further investigation, this appears to be an issue with FastAPI. Lifespan events are not supported by routers. See https://github.com/tiangolo/fastapi/discussions/9664

Possible workaround that occur to me:
1.  do it all on the main `app`. This seems a bit messy to me.
2. use the, supposedly deprecated, `startup_event`. 

I've tried the secind, but can't get that to work:
`router.py`
```python
client = None


@router.on_event("startup")
async def startup_event():
    print("Starting MQTT client")
    global client
    async with aiomqtt.Client("test.mosquitto.org") as c:
        # Make client globally available
        client = c
        # Listen for MQTT messages in (unawaited) asyncio task
        loop = asyncio.get_event_loop()
        loop.create_task(listen(client))
```

I now get this error:
```
    raise MqttCodeError(info.rc, "Could not publish message")
aiomqtt.error.MqttCodeError: [code:4] The client is not currently connected.
```

**Comment by empicano** [comment]
Hi there!

That's good to know that the approach doesn't work for FastAPI routers. As you said, the best way forward would be to bring this up with the FastAPI team.

With regards to your workaround: The aiomqtt client connects inside the `startup_event` function, but then also exits the context manager again before the function returns, which disconnects the client.

The trick with our lifespan example is that we `yield` inside the context manager. This way the client connects, then all the requests are handled, and only _after_ the FastAPI application exits does the yield "return" so to say and we exit the aiomqtt context manager.

I haven't worked with FastAPI in a bit. If there's a corresponding "shutdown" event, you could use the context manager's [`__aenter__` and `__aexit__` methods](https://github.com/sbtinstruments/aiomqtt/blob/225c1bfc99bc6ff908bd03c1115963e43ab8a9e6/aiomqtt/client.py#L887) directly (call `__aenter__` during startup and `__aexit__` during shutdown). We _do not_ recommend this approach, it's a workaround and a bit tricky to get right. The best option would be that FastAPI supports lifespans for routers.

Let me know if that helps! 😊

**Comment by tomliptrot** [comment]
Thanks so much for your quick response. I've done what you suggested (called `__aenter__` during startup and `__aexit__` during shutdown) and it seems to be working.

In case anybody else finds this issue before FastAPI adds lifespan event to routers. This is how I did it:


```python
# router.py

@router.on_event("startup")
async def startup_event():
    print("Starting MQTT client")
    global client
    client = aiomqtt.Client("test.mosquitto.org")
    await client.__aenter__()
    print("MQTT client started")
    loop = asyncio.get_event_loop()
    loop.create_task(listen(client))

@router.on_event("shutdown")
async def shutdown_event():
    print("Stopping MQTT client")
    await client.__aexit__()
    print("MQTT client stopped")
```

@empicano what are the risks/downside of using this approach?

**Comment by empicano** [comment]
Looks good so far 👍 You need to keep a reference to the listener task you create and call `cancel()` on it during shutdown. The original lifespan example and [this section in the docs](https://sbtinstruments.github.io/aiomqtt/subscribing-to-a-topic.html#stop-listening) show how.

**Comment by tomliptrot** [comment]
Like this with another global variable?:

```python
client = None
task = None

@router.on_event("startup")
async def startup_event():
    print("Starting MQTT client")
    global client
    client = aiomqtt.Client("test.mosquitto.org")
    await client.__aenter__()
    print("MQTT client started")
    loop = asyncio.get_event_loop()
    global task
    task = loop.create_task(listen(client))

@router.on_event("shutdown")
async def shutdown_event():
    print("Stopping MQTT client")
    task.cancel()
    await client.__aexit__(None, None, None)
    print("MQTT client stopped")
```

Yep, that worked. No more errors.

When you say you don't recommend this approach, why is that? What are the risks/downsides?

**Comment by empicano** [comment]
Great 👍😎

Context managers ensure that the setup and teardown code of an external resource is executed at least, and at most once.

There are a few cases where this can go wrong when using `__aenter__` and `__aexit__` directly:

If we throw an exception inside the `shutdown_event` function before we have the chance to call `__aexit__`, the resource won't be properly closed -- the client stays connected. This may not be an immediate problem for a simple use case, but if we deal with many connections this can become a problem. (That's why we manage files with context managers in Python as well, we don't want to forget to close them and run out of memory.)

Similarly, if we have complex code, we might forget to call `__aexit__` in some obscure execution path. Or call it multiple times. Or call `__aexit__` before `__aenter__` etc.

**Comment by tomliptrot** [comment]
That makes perfect sense. Thanks so much @empicano for solving my issue and your prompt and incredibly clear explanation. 

Let me know if I can do anything to help with this excellent library.

**Comment by frederikaalund** [comment]
Well done, @empicano! 😄👍
