### ISSUE TITLE
Topic `topic/subtopic` does not match wildcard `topic/subtopic/#`

### ISSUE THREAD

**Issue by steersbob** [sbtinstruments/aiomqtt#239]
For reference: <https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180920>, section 4.7.1.2

> Non normative comment
>
> For example, if a Client subscribes to “sport/tennis/player1/#”, it would receive messages published using these topic names:
> ·         “sport/tennis/player1”
> ·         “sport/tennis/player1/ranking”
> ·         “sport/tennis/player1/score/wimbledon”

Observed behavior for aiomqtt 1.0.0 is:

```
Python 3.9.9 (main, Aug 13 2022, 23:00:17) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from aiomqtt import Topic
>>> Topic('sports/tennis/player1').matches('sports/tennis/player1/#')
False
>>> 
```

**Comment by empicano** [comment]
Hi Bob,

Good catch! I actually didn't know this, but the documentation is clear on it.

Do you want to make a PR to fix it? 🙂

**Comment by steersbob** [comment]
Yes, my intention is to send a PR once I'm done with the housekeeping involved in migrating our packages from the old aiomqtt.
