### ISSUE TITLE
Topic is always evaluated to the wrong type because of decorator

### ISSUE THREAD

**Issue by tsturzl** [sbtinstruments/aiomqtt#242]
In the definition of the `subscribe` and `unsubscribe` I see that topic is defined as `SubscribeTopic` type, which can be defined as a number of things but most simply can be defined as just an ordinary string. For `publish` the topic is defined strictly as a string type. In either case passing a string seems to fail type checking with the error "Expected type ClientT, got str instead". Doing a little digging it would seem this `_outgoing_call` decorator is the culprit. It expects to decorate a method with the signature `Callable[Concatenate[ClientT, P], Coroutine[Any, Any, T]]`, I assume that this implies that the method being decorated is a method where ClientT represents the type that self should be. This seems to not work well with all type checking, and in my case topic is being expected to be of type `ClientT`. Even if I specifically state that I'm passing the topic I still get a type error, eg `client.publish(topic=topic ...)` still gives the same type error. I notice that if I remove that from the type definitions the type error goes away on my end, though I'm not sure if that complicates the typing for aiomqtt in some way.

I see there is a note to redo this portion, and while the issue is annoying it obviously doesn't impact runtime. I just figured I would bring this up so you're made aware of the issue. This is very low priority, but worth considering if you have time or during a refactor. Thanks for putting this project together, was very helpful to get a paho client into an application than heavily relies on asyncio.

**Comment by vvanglro** [comment]
@tsturzl Hi, If you use pycharm, Here are the relevant reasons: https://github.com/sbtinstruments/aiomqtt/pull/211#issuecomment-1545494330
