### ISSUE TITLE
FEATURE: asyncio_mqtt UNIX sock support

### ISSUE THREAD

**Issue by fariz-muradov-inno2grid** [sbtinstruments/aiomqtt#259]
I wonder does this library support UNIX sock file or not to connect ECLIPSE MOSQUITTO via MQTT protocol?

**Comment by empicano** [comment]
Hi there,

Thanks for this issue and sorry for the late reply on this!

I don't think it does. I can't find much on the subject, can you point me to some resources explaining this further? As aiomqtt is built on top of paho-mqtt, we can only support features that paho-mqtt itself implements. @frederikaalund, do you know more about this?

**Comment by frederikaalund** [comment]
Hi Fariz, thank you for opening this issue.

The short answer is: No, unfortunately we do not support Unix domain sockets. Like @empicano already mentioned, we support the same connection feature set as the underlying paho-mqtt library.

Depending on your use case, you could "pipe" the UDS to TCP via, e.g., `ssh`, `socat` or the like. That, however, is out of scope of what we can assist you with here in this bugtracker.

I hope that helps you solve your issue.

**Comment by fariz-muradov-inno2grid** [comment]
Thanks. I am using socat already. Just looked some way to make native configs.

Thanks a lot for response and clarifications.



TLP:GREEN

From: Frederik Aalund ***@***.***>
Date: Tuesday, 23 January 2024 at 10:40
To: sbtinstruments/aiomqtt ***@***.***>
Cc: Fariz Muradov ***@***.***>, Author ***@***.***>
Subject: Re: [sbtinstruments/aiomqtt] FEATURE: asyncio_mqtt UNIX sock support (Issue #259)

Hi Fariz, thank you for opening this issue.

The short answer is: No, unfortunately we do not support Unix domain sockets. Like @empicano<https://github.com/empicano> already mentioned, we support the same connection feature set as the underlying paho-mqtt library.

Depending on your use case, you could "pipe" the UDS to TCP via, e.g., ssh, socat or the like. That, however, is out of scope of what we can assist you with here in this bugtracker.

I hope that helps you solve your issue.
