### ISSUE TITLE
Typing warnings in IDE on Client methods

### ISSUE THREAD

**Issue by alyahmady** [sbtinstruments/aiomqtt#270]
Hi. I get warning on `aiomqtt.Client` methods' calls.

Here are the warnings:
![image](https://github.com/sbtinstruments/aiomqtt/assets/47256758/74cd78d4-8407-4e02-b5c7-c13546307cc7)
![image](https://github.com/sbtinstruments/aiomqtt/assets/47256758/a9621036-d7e2-4ecc-8f64-1fbaafc593f0)

Here's a full example of source code:
```python
async def main(mqtt_topic: str):
    logger: logging.Logger

    async with Client(
        hostname=lorem,
        port=lorem,
        username=lorem,
        password=lorem,
        transport=lorem,
        websocket_path=lorem,
        tls_params=lorem,
        tls_insecure=None if not Config.enable_tls else False,
    ) as client:
        logger.debug("Connected")

        async with client.messages() as messages:
            logger.debug("Subscribing on %s/#", mqtt_topic)

            await client.subscribe(f"{mqtt_topic}/#")

            logger.debug("Subscribed on %s/#", mqtt_topic)

            async for message in messages:
                logger.debug("Received message on %s: %s", mqtt_topic, message.payload)
```

Also, as an optional feature, it's much expected to have typing on `message` in each iteration, while looping through `client.messages`.

![image](https://github.com/sbtinstruments/aiomqtt/assets/47256758/a9eb03f8-a0df-4463-9430-790831465278)

My Environment:
PyCharm 2023.3.2
Python 3.11.3
`aiomqtt==1.2.1`
`paho-mqtt==1.6.1`
OS: Both Ubuntu 22.04 and Windows 11

**Comment by vvanglro** [comment]
The problem of pycharm. It is recommended to use vscode to open it.

Vscode uses pyright for type detection.

**Comment by empicano** [comment]
Here's some more context: https://github.com/sbtinstruments/aiomqtt/pull/211#issuecomment-1545494330

I don't think we can fix this from our side, that has to be done in PyCharm.
