### ISSUE TITLE
Make aiomqtt compatible with paho v2

### ISSUE THREAD

**Issue by JonathanPlasse** [sbtinstruments/aiomqtt#279]
We could use `paho.mqtt.__version__` to determine at runtime whether to pass `mqtt.CallbackAPIVersion.VERSION1` to the init call to the paho client.
```python
if mqtt.__version__.startswith("2"):
    client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION1)
else:
   client = mqtt.Client()
```

**Comment by skewty** [comment]
Is there a compelling reason to not couple "^2.0" and work with it as it is by default?

I did a quick look at the paho v2 asyncio examples and it doesn't look like much has changed / changes look minimal.

**Comment by JonathanPlasse** [comment]
I will do the PR tonight.

**Comment by JonathanPlasse** [comment]
This is not as trivial as I thought, the typing and mypy are getting in the way.

**Comment by JonathanPlasse** [comment]
Hey @empicano, @frederikaalund,

Managing typings for both paho-mqtt 1.6.1 and the newer 2.0 version adds many complexities. Given that 1.6.1 is significantly outdated now, I'm leaning towards fully embracing version 2.0 and discontinuing support for the older one.

This will allow us to leverage the latest features and improvements in 2.0. What are your thoughts on making this transition?

**Comment by empicano** [comment]
Sounds sensible to me 👍 The extra maintenance burden doesn't seem worth it 🙂

**Comment by frederikaalund** [comment]
I agree, it sounds very sensible to drop support for the v1.x line of paho.mqtt.

**Comment by skewty** [comment]
Did this work move into another fork / repo or did development stall?  I am not seeing any changes in 5 days.

https://github.com/sbtinstruments/aiomqtt/commit/1862ead1f726893ea2b09051d75544c5fc69dc83

**Comment by skewty** [comment]
Will this go out to pypi as v2.1?

Currently testing it out (no issues so far):
```toml
[tool.poetry.dependencies]
aiomqtt = { git = "https://github.com/sbtinstruments/aiomqtt.git", rev = "8321217" }  # until > v2.0.1 released
```

**Comment by skewty** [comment]
Is some issue holding up a new pypi release?  If so, perhaps this issue should be re-opened with a link to that issue.
