### ISSUE TITLE
Exceptions on __aenter__ not handled.

### ISSUE THREAD

**Issue by kuriakosejohn** [sbtinstruments/aiomqtt#284]
We are using aiomqtt to connect to AWS IoT Core with client certificate and just in time registration, this means first connection to broker will fail with an `Operation Timed out` exception from line `client.py: __aenter__().await self._wait_for(self._connected, timeout=None)`. We have the following retry logic, but we continuously get  "MqttReentrantError" exception for following iterations since `self._lock` is not released and `self._connected` future is not re-initialized for the second call.

```python
while True:
    try:
       async with client:
          ...
```

The following change in `client.py: __aenter__()` solved the problem.
```diff
-        await self._wait_for(self._connected, timeout=None)
+        try:
+            await self._wait_for(self._connected, timeout=None)
+        except Exception as e:
+            self._lock.release()
+            self._connected = asyncio.Future()
+            raise e
```

**Comment by Gunsmithy** [comment]
Following since I was debugging this with John.
Feel free to reach out to either of us if we can help with a reproduction!

**Comment by empicano** [comment]
Thanks both of you for the issue and the solution, good catch! 😊
