### ISSUE TITLE
Do not send messages for a long time mqtt automatically disconnects

### ISSUE THREAD

**Issue by 0716gzs** [sbtinstruments/aiomqtt#295]
When I use aiomqtt to connect to mqtt after an hour without sending mqtt messages, the following error occurs: aiomqtt. exceptions.MqttCodeError: [code:16] Client or broker did not communicate in the keepalive interval.

However, I see the underlying default keepalive is 60. What is the reason for this

**Comment by empicano** [comment]
This exception is raised in the underlying paho-mqtt library and aiomqtt only propagates it in a custom exception. On first glance, we probably can't solve this inside aiomqtt, could you check the paho-mqtt project, maybe there's some info on this over there? [This issue](https://github.com/eclipse/paho.mqtt.python/issues/683) and [this one](https://github.com/eclipse/paho.mqtt.python/issues/731) seem related (code 16) for example.

**Comment by empicano** [comment]
I'll tentatively close this as there have been no further responses. If it is still a problem, please feel free to reopen! 🙂
