### ISSUE TITLE
FastAPI Shared Client Connection

### ISSUE THREAD

**Issue by odie5533** [sbtinstruments/aiomqtt#320]
Hi. I'm trying to integrate with FastAPI and share the connection around my app. I'm following the [Alongside FastAPI & Co. guide](https://sbtinstruments.github.io/aiomqtt/alongside-fastapi-and-co.html), but it's a single file which doesn't overcome the pitfalls I'm running into. The issue I have is that of either circular imports or an uninitialized client from importing it too early.

e.g. circular import:
```python
"""FastAPI router with a single endpoint to toggle a switch."""
import fastapi
from mqtt_service.main import client

router = fastapi.APIRouter()

@router.get("/switch")
async def switch():
    """Toggle the switch."""
    await client.publish("switch/toggle", 1)
    return {"message": "Switch toggled"}
```

I can declare the client earlier in my main.py, but I get `AttributeError: 'NoneType' object has no attribute 'publish'` when my endpoint tries to use it because I've imported client before it gets assigned:
```python
# main.py
import asyncio, aiomqtt, fastapi

client: aiomqtt.Client = None

from mqtt_service.routes import switch
```
---

My solution so far is this, but I'm wondering if there's a smarter way? Or is this a good method?

```python
from contextlib import asynccontextmanager
import aiomqtt

client = None

class MQTTClient(aiomqtt.Client):
    def __new__(cls) -> aiomqtt.Client:
        global client
        if client is None:
            raise RuntimeError("MQTT client is not connected")
        return client

@asynccontextmanager
async def mqtt_lifespan():
    global client
    async with aiomqtt.Client("test.mosquitto.org") as c:
        client = c
        try:
            yield c
        finally:
            client = None
```

```python
"""FastAPI router with a single endpoint to toggle a switch."""
from typing import Annotated
import fastapi
from fastapi import Depends
from mqtt_service.mqtt_client import MQTTClient

router = fastapi.APIRouter()

@router.get("/switch")
async def switch(mqttc: Annotated[MQTTClient, Depends()]):
    """Toggle the switch."""
    await mqttc.publish("sh/toggle", 1)
    return {"message": "Switch toggled"}
```

**Comment by empicano** [comment]
Hi there! 😋

(Disclaimer: I haven't worked with FastAPI for a bit) I'd try to manage the aiomqtt client like a database connection. Your solution is definitely going in the right direction 👍 I'm not sure why you need the extra class, however, the client should never be `None` when we initialize it in the lifespan function. Shouldn't something like this work as well?

```python
import asyncio
import aiomqtt
import contextlib
import fastapi


client = None


def mqtt():
    yield client


@contextlib.asynccontextmanager
async def lifespan(app):
    global client
    async with aiomqtt.Client("test.mosquitto.org") as c:
        # Make client globally available
        client = c
        yield


app = fastapi.FastAPI(lifespan=lifespan)


@app.get("/")
async def publish(client=fastapi.Depends(mqtt)):
    await client.publish("humidity/outside", 0.38)
```

I'd happily accept a PR with a section in our docs on this 🙂
